build:
	cd ./apps/cli/ && \
	cargo build \
		--release \
		--target x86_64-pc-windows-gnu \
	&& \
	cargo build \
		--release \
		--target x86_64-pc-windows-gnu
	
	# cp ./target/x86_64-pc-windows-gnu/debug/tot ${BEATSABER_DIRECTORY}
