// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_trpc_trpc_ from "./routes/api/trpc/[trpc].ts";
import * as $api_v1_discord_command_webhook from "./routes/api/v1/discord/command-webhook.tsx";
import * as $api_v1_discord_playlist_get_guild_guildId_channel_channelId_ from "./routes/api/v1/discord/playlist/get/guild/[guildId]/channel/[channelId].tsx";
import * as $api_v1_discord_playlist_get_guild_guildId_channel_channelId_download from "./routes/api/v1/discord/playlist/get/guild/[guildId]/channel/[channelId]/download.tsx";
import * as $api_v1_discord_playlist_get_guild_guildId_channel_channelId_oneclick_desiredFileName_ from "./routes/api/v1/discord/playlist/get/guild/[guildId]/channel/[channelId]/oneclick/[desiredFileName].tsx";
import * as $api_v1_playlist_get_playlistIdWithFileExtension_ from "./routes/api/v1/playlist/get/[playlistIdWithFileExtension].tsx";
import * as $api_v1_playlist_get_playlistIdWithFileExtension_beatleader_player_playerId_ from "./routes/api/v1/playlist/get/[playlistIdWithFileExtension]/beatleader/player/[playerId].ts";
import * as $api_v1_playlist_get_playlistIdWithFileExtension_beatleader_player_playerId_unplayed from "./routes/api/v1/playlist/get/[playlistIdWithFileExtension]/beatleader/player/[playerId]/unplayed.ts";
import * as $api_v1_playlist_get_playlistIdWithFileExtension_download from "./routes/api/v1/playlist/get/[playlistIdWithFileExtension]/download.tsx";
import * as $api_v1_playlist_get_playlistIdWithFileExtension_oneclick_desiredFileName_ from "./routes/api/v1/playlist/get/[playlistIdWithFileExtension]/oneclick/[desiredFileName].tsx";
import * as $editor_playlist_list from "./routes/editor/playlist/list.tsx";
import * as $home_layout from "./routes/home/_layout.tsx";
import * as $home_collection_list from "./routes/home/collection/list.tsx";
import * as $home_index from "./routes/home/index.tsx";
import * as $home_playlist_playlistId_beatleader_player_playerId_ from "./routes/home/playlist/[playlistId]/beatleader/player/[playerId].tsx";
import * as $home_playlist_playlistId_details from "./routes/home/playlist/[playlistId]/details.tsx";
import * as $home_playlist_list from "./routes/home/playlist/list.tsx";
import * as $index from "./routes/index.tsx";
import * as $Button from "./islands/Button.tsx";
import * as $CopyButton from "./islands/CopyButton.tsx";
import * as $LinkButton from "./islands/LinkButton.tsx";
import * as $playlist_PlaylistDetails from "./islands/playlist/PlaylistDetails.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/trpc/[trpc].ts": $api_trpc_trpc_,
    "./routes/api/v1/discord/command-webhook.tsx": $api_v1_discord_command_webhook,
    "./routes/api/v1/discord/playlist/get/guild/[guildId]/channel/[channelId].tsx":
      $api_v1_discord_playlist_get_guild_guildId_channel_channelId_,
    "./routes/api/v1/discord/playlist/get/guild/[guildId]/channel/[channelId]/download.tsx":
      $api_v1_discord_playlist_get_guild_guildId_channel_channelId_download,
    "./routes/api/v1/discord/playlist/get/guild/[guildId]/channel/[channelId]/oneclick/[desiredFileName].tsx":
      $api_v1_discord_playlist_get_guild_guildId_channel_channelId_oneclick_desiredFileName_,
    "./routes/api/v1/playlist/get/[playlistIdWithFileExtension].tsx": $api_v1_playlist_get_playlistIdWithFileExtension_,
    "./routes/api/v1/playlist/get/[playlistIdWithFileExtension]/beatleader/player/[playerId].ts":
      $api_v1_playlist_get_playlistIdWithFileExtension_beatleader_player_playerId_,
    "./routes/api/v1/playlist/get/[playlistIdWithFileExtension]/beatleader/player/[playerId]/unplayed.ts":
      $api_v1_playlist_get_playlistIdWithFileExtension_beatleader_player_playerId_unplayed,
    "./routes/api/v1/playlist/get/[playlistIdWithFileExtension]/download.tsx":
      $api_v1_playlist_get_playlistIdWithFileExtension_download,
    "./routes/api/v1/playlist/get/[playlistIdWithFileExtension]/oneclick/[desiredFileName].tsx":
      $api_v1_playlist_get_playlistIdWithFileExtension_oneclick_desiredFileName_,
    "./routes/editor/playlist/list.tsx": $editor_playlist_list,
    "./routes/home/_layout.tsx": $home_layout,
    "./routes/home/collection/list.tsx": $home_collection_list,
    "./routes/home/index.tsx": $home_index,
    "./routes/home/playlist/[playlistId]/beatleader/player/[playerId].tsx":
      $home_playlist_playlistId_beatleader_player_playerId_,
    "./routes/home/playlist/[playlistId]/details.tsx": $home_playlist_playlistId_details,
    "./routes/home/playlist/list.tsx": $home_playlist_list,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Button.tsx": $Button,
    "./islands/CopyButton.tsx": $CopyButton,
    "./islands/LinkButton.tsx": $LinkButton,
    "./islands/playlist/PlaylistDetails.tsx": $playlist_PlaylistDetails,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
