// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_v1_discord_command_webhook from "./routes/api/v1/discord/command-webhook.tsx";
import * as $api_v1_discord_playlist_get_guild_guildId_channel_channelId_ from "./routes/api/v1/discord/playlist/get/guild/[guildId]/channel/[channelId].tsx";
import * as $api_v1_discord_playlist_get_guild_guildId_channel_channelId_download from "./routes/api/v1/discord/playlist/get/guild/[guildId]/channel/[channelId]/download.tsx";
import * as $api_v1_discord_playlist_get_guild_guildId_channel_channelId_oneclick_desiredFileName_ from "./routes/api/v1/discord/playlist/get/guild/[guildId]/channel/[channelId]/oneclick/[desiredFileName].tsx";
import * as $api_v1_playlist_get_playlistIdWithFileExtension_ from "./routes/api/v1/playlist/get/[playlistIdWithFileExtension].tsx";
import * as $api_v1_playlist_get_playlistIdWithFileExtension_download from "./routes/api/v1/playlist/get/[playlistIdWithFileExtension]/download.tsx";
import * as $api_v1_playlist_get_playlistIdWithFileExtension_oneclick_desiredFileName_ from "./routes/api/v1/playlist/get/[playlistIdWithFileExtension]/oneclick/[desiredFileName].tsx";
import * as $home_layout from "./routes/home/_layout.tsx";
import * as $home_collection_list from "./routes/home/collection/list.tsx";
import * as $home_index from "./routes/home/index.tsx";
import * as $home_playlist_playlistId_details from "./routes/home/playlist/[playlistId]/details.tsx";
import * as $home_playlist_list from "./routes/home/playlist/list.tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/v1/discord/command-webhook.tsx": $api_v1_discord_command_webhook,
    "./routes/api/v1/discord/playlist/get/guild/[guildId]/channel/[channelId].tsx":
      $api_v1_discord_playlist_get_guild_guildId_channel_channelId_,
    "./routes/api/v1/discord/playlist/get/guild/[guildId]/channel/[channelId]/download.tsx":
      $api_v1_discord_playlist_get_guild_guildId_channel_channelId_download,
    "./routes/api/v1/discord/playlist/get/guild/[guildId]/channel/[channelId]/oneclick/[desiredFileName].tsx":
      $api_v1_discord_playlist_get_guild_guildId_channel_channelId_oneclick_desiredFileName_,
    "./routes/api/v1/playlist/get/[playlistIdWithFileExtension].tsx": $api_v1_playlist_get_playlistIdWithFileExtension_,
    "./routes/api/v1/playlist/get/[playlistIdWithFileExtension]/download.tsx":
      $api_v1_playlist_get_playlistIdWithFileExtension_download,
    "./routes/api/v1/playlist/get/[playlistIdWithFileExtension]/oneclick/[desiredFileName].tsx":
      $api_v1_playlist_get_playlistIdWithFileExtension_oneclick_desiredFileName_,
    "./routes/home/_layout.tsx": $home_layout,
    "./routes/home/collection/list.tsx": $home_collection_list,
    "./routes/home/index.tsx": $home_index,
    "./routes/home/playlist/[playlistId]/details.tsx": $home_playlist_playlistId_details,
    "./routes/home/playlist/list.tsx": $home_playlist_list,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
