name: Deploy

on: push

jobs:
  discord-bot_deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
        with:
          token: ${{ secrets.DENO_DEPLOY_TOKEN }}
          project: danielduel-tot-bot
          entrypoint: apps/discord-bot/main.ts
          exclude: |
            data
            migrated
            assets
            public
            scripts

  editor_deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
        with:
          project: tower-of-tech-editor
          entrypoint: apps/editor/server.tsx

  discord-bot_register-commands:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Register discord commands
        env:
          DISCORD_TOT_BOT_CLIENT_ID: ${{ secrets.DISCORD_TOT_BOT_CLIENT_ID }}
          DISCORD_TOT_BOT_TOKEN: ${{ secrets.DISCORD_TOT_BOT_TOKEN }}
        run: |
          deno task discord-bot:register-raw
