name: Deploy

on: push

jobs:
  discord-bot_deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            apps
            packages
            src
            deno.json
            deno.lock
            importMap.json
            importMap.local.json

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: danielduel-tot-bot
          entrypoint: apps/discord-bot/main.ts
          exclude: |
            data
            migrated
            assets
            public
            scripts

  editor_deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            apps
            packages
            src
            deno.json
            deno.lock
            importMap.json
            importMap.local.json

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: tower-of-tech-editor
          entrypoint: apps/editor/server.tsx
          exclude: |
            data
            migrated
            assets
            public
            scripts

  discord-bot_register-commands:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Register discord commands
        env:
          DISCORD_TOT_BOT_CLIENT_ID: ${{ secrets.DISCORD_TOT_BOT_CLIENT_ID }}
          DISCORD_TOT_BOT_TOKEN: ${{ secrets.DISCORD_TOT_BOT_TOKEN }}
        run: |
          deno task discord-bot:register-raw
